export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_NEW = 'REGISTRATION_NEW';

export const GET_LIST_START = 'GET_LIST_START';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_ERROR = 'GET_LIST_ERROR';

export const CREATE_INCOME_OR_EXPENSES_ITEM_START = 'CREATE_INCOME_OR_EXPENSES_ITEM_START';
export const CREATE_INCOME_OR_EXPENSES_ITEM_SUCCESS = 'CREATE_INCOME_OR_EXPENSES_ITEM_SUCCESS';
export const CREATE_INCOME_OR_EXPENSES_ITEM_ERROR = 'CREATE_INCOME_OR_EXPENSES_ITEM_ERROR';

export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

export const GET_CATEGORYS_START = 'GET_CATEGORYS_START';
export const GET_CATEGORYS_SUCCESS = 'GET_CATEGORYS_SUCCESS';
export const GET_CATEGORYS_ERROR = 'GET_CATEGORYS_ERROR';